---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      pod-app: my-app
  template:
    metadata:
      labels:
        pod-app: my-app
    spec:
      containers:
        - name: app-container
          image: hzgl/k8s-hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: app-load-balancer
spec:
  type: LoadBalancer
  selector:
    pod-app: my-app
  ports:
    - protocol: TCP
      port: 20000
